source 'https://rubygems.org'

ruby '~> 3.3'

gem 'bootsnap', require: false
gem 'jbuilder', '~> 2.0'
gem 'nokogiri', '~> 1.18'
gem 'puma', '~> 6.0'
gem 'rails', '~> 8.0'

# Native gem with platform variants
gem 'ffi', '~> 1.17'

# Git source: tests GIT section parsing (TODO #13)
gem 'errgonomic', git: 'https://github.com/omc/errgonomic.git', branch: 'main'

# Path source: tests PATH section parsing (TODO #13)
gem 'hello_gem', path: 'vendor/hello_gem'

group :development, :test do
  gem 'minitest', '~> 5.0'
  gem 'rake', '~> 13.0'
end

group :development do
  gem 'rack', '~> 3.0'
end
